{\rtf1\ansi\ansicpg1252\cocoartf2638
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fmodern\fcharset0 CourierNewPSMT;}
{\colortbl;\red255\green255\blue255;\red98\green94\blue76;\red249\green249\blue249;\red19\green152\blue188;
\red205\green110\blue6;\red19\green151\blue241;\red244\green0\blue95;\red14\green14\blue14;\red107\green32\blue255;
\red29\green30\blue26;}
{\*\expandedcolortbl;;\cssrgb\c45882\c44314\c36863;\cssrgb\c98039\c98039\c98039;\cssrgb\c0\c65882\c78431;
\cssrgb\c84706\c50980\c0;\cssrgb\c1176\c66275\c95686;\cssrgb\c97647\c14902\c44706;\cssrgb\c6667\c6667\c6667;\cssrgb\c50196\c27059\c100000;
\cssrgb\c15294\c15686\c13333;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs27\fsmilli13920 \AppleTypeServices\AppleTypeServicesF65539 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 # Specify the parent image from which we build\
\pard\pardeftab720\partightenfactor0
\cf4 \cb3 \strokec4 FROM\cf5 \strokec5  stereolabs/zed:3.7-gl-devel-cuda11.4-ubuntu20.04\
\
\pard\pardeftab720\partightenfactor0
\cf2 \cb3 \strokec2 # Set the working directory\
\pard\pardeftab720\partightenfactor0
\cf4 \cb3 \strokec4 WORKDIR\cf5 \strokec5  /Src\
\
\cf4 \strokec4 COPY\cf6 \cb3 \strokec6  cpp AppV2\
\
\pard\pardeftab720\partightenfactor0
\cf2 \cb3 \strokec2 # Build the application with cmake\
\pard\pardeftab720\partightenfactor0
\cf4 \cb3 \strokec4 RUN\cf6 \cb3 \strokec6  mkdir /app/hello_zed_src/build \cf7 \cb3 \strokec7 &&\cf6 \cb3 \strokec6  \cf8 \cb3 \strokec8 cd\cf6 \cb3 \strokec6  /Src/ \cf7 \cb3 \strokec7 &&\cf6 \cb3 \strokec6  \cf9 \cb3 \strokec9 \\\
\pard\pardeftab720\partightenfactor0
\cf6 \cb3 \strokec6     cmake -DCMAKE_LIBRARY_PATH\cf7 \cb3 \strokec7 =\cf6 \cb3 \strokec6 /usr/local/cuda/lib64/stubs \cf9 \cb3 \strokec9 \\\
\cf6 \cb3 \strokec6       -DCMAKE_CXX_FLAGS\cf7 \cb3 \strokec7 =\cf5 \cb3 \strokec5 "-Wl,--allow-shlib-undefined"\cf6 \cb3 \strokec6  .. \cf7 \cb3 \strokec7 &&\cf6 \cb3 \strokec6  \cf9 \cb3 \strokec9 \\\
\cf6 \cb3 \strokec6     make
\fs32 \AppleTypeServices \cf10 \cb3 \strokec10 \
\
\pard\pardeftab720\partightenfactor0

\fs27\fsmilli13920 \AppleTypeServices\AppleTypeServicesF65539 \cf2 \cb3 \strokec2 # Run the application\
\pard\pardeftab720\partightenfactor0
\cf4 \cb3 \strokec4 CMD\cf6 \cb3 \strokec6  \cf8 \cb3 \strokec8 [\cf5 \cb3 \strokec5 \'93/Src/AppV2\'94\cf8 \cb3 \strokec8 ]
\fs32 \AppleTypeServices \cf10 \strokec10 \
}