program: Src/DeepFMTrainingWandb.py
method: bayes
metric:
  name: val_loss
  goal: minimize
parameters:
  weight_decay: 
    min: 0.00001
    max: 0.001
  lr: 
    min: 0.00001
    max: 0.005
  latent_dim1: 
    min: 4
    max: 64
  latent_dim2: 
    min: 4
    max: 128
  latent_dim3: 
    min: 4
    max: 64
  embed_dim: 
    min: 4
    max: 64
  dropout: 
    min: 0.2
    max: 0.5
  pos_weight: 
    min: 3
    max: 200
